/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Scientific_calculate;

import java.awt.event.KeyEvent;

/**
 *
 * @author waliy
 */
public class Scientific_cal extends javax.swing.JFrame {
    
    double FirstNum;
    double SecondNum;
    double Result;
    String operations;
    private Object math;

    /**
     * Creates new form Scientific_cal
     */
    public Scientific_cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextDisplay = new javax.swing.JTextField();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnPlus = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnMultiply = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnDivide = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jBtnEquals = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnDecimal = new javax.swing.JButton();
        jBtnSquareRoot = new javax.swing.JButton();
        jBtnMinus = new javax.swing.JButton();
        jbtnBackspace = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jBtnCos = new javax.swing.JButton();
        jBtnHex = new javax.swing.JButton();
        jBtnCosh = new javax.swing.JButton();
        jBtnTan = new javax.swing.JButton();
        jBtnX3 = new javax.swing.JButton();
        jBtnTanh = new javax.swing.JButton();
        jBtnSin = new javax.swing.JButton();
        jBtnSinh = new javax.swing.JButton();
        jBtnXY = new javax.swing.JButton();
        jBtnCbr = new javax.swing.JButton();
        jBtnLog = new javax.swing.JButton();
        jBtnRund = new javax.swing.JButton();
        jBtnX2 = new javax.swing.JButton();
        jBtnPi = new javax.swing.JButton();
        jBtnBin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTextDisplay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDisplayKeyTyped(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtnPlus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnPlus.setText("+");
        jBtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlusActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtnMultiply.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnMultiply.setText("*");
        jBtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiplyActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtnDivide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDivide.setText("/");
        jBtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivideActionPerformed(evt);
            }
        });

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setText("±");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jBtnEquals.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnEquals.setText("=");
        jBtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualsActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtn0.setText("0");

        jBtnDecimal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDecimal.setText(".");
        jBtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDecimalActionPerformed(evt);
            }
        });

        jBtnSquareRoot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSquareRoot.setText("√");
        jBtnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSquareRootActionPerformed(evt);
            }
        });

        jBtnMinus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnMinus.setText("-");
        jBtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMinusActionPerformed(evt);
            }
        });

        jbtnBackspace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnBackspace.setText("←");
        jbtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackspaceActionPerformed(evt);
            }
        });

        jBtnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnClear.setText("C");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jBtnCos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCos.setText("Cos");
        jBtnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCosActionPerformed(evt);
            }
        });

        jBtnHex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnHex.setText("Hex");
        jBtnHex.setToolTipText("");
        jBtnHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHexActionPerformed(evt);
            }
        });

        jBtnCosh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCosh.setText("Cosh");
        jBtnCosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCoshActionPerformed(evt);
            }
        });

        jBtnTan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnTan.setText("Tan");
        jBtnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTanActionPerformed(evt);
            }
        });

        jBtnX3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnX3.setText("x^3");
        jBtnX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnX3ActionPerformed(evt);
            }
        });

        jBtnTanh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnTanh.setText("Tanh");
        jBtnTanh.setToolTipText("");
        jBtnTanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTanhActionPerformed(evt);
            }
        });

        jBtnSin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSin.setText("Sin");
        jBtnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSinActionPerformed(evt);
            }
        });

        jBtnSinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnSinh.setText("Sinh");
        jBtnSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSinhActionPerformed(evt);
            }
        });

        jBtnXY.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnXY.setText("x^y");
        jBtnXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnXYActionPerformed(evt);
            }
        });

        jBtnCbr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCbr.setText("Cbr");
        jBtnCbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCbrActionPerformed(evt);
            }
        });

        jBtnLog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnLog.setText("Log");
        jBtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLogActionPerformed(evt);
            }
        });

        jBtnRund.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnRund.setText("Rund");
        jBtnRund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRundActionPerformed(evt);
            }
        });

        jBtnX2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnX2.setText("x^2");
        jBtnX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnX2ActionPerformed(evt);
            }
        });

        jBtnPi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnPi.setText("π");
        jBtnPi.setToolTipText("");
        jBtnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPiActionPerformed(evt);
            }
        });

        jBtnBin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnBin.setText("Bin");
        jBtnBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBinActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextDisplay)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCbr, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRund, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnXY, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jBtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnX3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnBin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnHex, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTextDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnDecimal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnXY, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnCbr, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnRund, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnX3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBtnBin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnHex, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       this.setResizable(true);
       this.setSize(250, 400);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       this.setResizable(true);
       this.setSize(250, 400);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       this.setResizable(true);
       this.setSize( 480, 400);
       jTextDisplay.setSize(445, 39);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        String iNum = jTextDisplay.getText()+jBtn7.getText();
        jTextDisplay.setText(iNum);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
       String iNum = jTextDisplay.getText()+jBtn8.getText();
        jTextDisplay.setText(iNum);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        String iNum = jTextDisplay.getText()+jBtn9.getText();
        jTextDisplay.setText(iNum);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        String iNum = jTextDisplay.getText()+jBtn4.getText();
        jTextDisplay.setText(iNum);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
       String iNum = jTextDisplay.getText()+jBtn5.getText();
        jTextDisplay.setText(iNum);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        String iNum = jTextDisplay.getText()+jBtn6.getText();
        jTextDisplay.setText(iNum);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
       String iNum = jTextDisplay.getText()+jBtn1.getText();
        jTextDisplay.setText(iNum);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        String iNum = jTextDisplay.getText()+jBtn2.getText();
        jTextDisplay.setText(iNum);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
       String iNum = jTextDisplay.getText()+jBtn3.getText();
        jTextDisplay.setText(iNum);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
         jTextDisplay.setText("");
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jbtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackspaceActionPerformed
        String bsp = null;
        
        if (jTextDisplay.getText().length() > 0)
        {
            StringBuilder strB = new StringBuilder(jTextDisplay.getText());
            strB.deleteCharAt(jTextDisplay.getText().length() - 1);
            bsp = strB.toString();
            jTextDisplay.setText(bsp);
        }
    }//GEN-LAST:event_jbtnBackspaceActionPerformed

    private void jBtnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDecimalActionPerformed
        if (!jTextDisplay.getText().contains("."))
        {
            jTextDisplay.setText(jTextDisplay.getText() + jBtnDecimal.getText());
            
        }
    }//GEN-LAST:event_jBtnDecimalActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = ops * (-1);
        jTextDisplay.setText(String.valueOf(ops));
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jBtnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSquareRootActionPerformed
         double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.sqrt(ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnSquareRootActionPerformed

    private void jBtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLogActionPerformed
         double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.log(ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnLogActionPerformed

    private void jBtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivideActionPerformed
         FirstNum = Double.parseDouble(jTextDisplay.getText());
         jTextDisplay.setText(null);
         operations=("/");
    }//GEN-LAST:event_jBtnDivideActionPerformed

    private void jBtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMinusActionPerformed
        FirstNum = Double.parseDouble(jTextDisplay.getText());
         jTextDisplay.setText(null);
         operations=("-");
    }//GEN-LAST:event_jBtnMinusActionPerformed

    private void jBtnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSinActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.sin(ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnSinActionPerformed

    private void jBtnSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSinhActionPerformed
         double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.sinh(ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnSinhActionPerformed

    private void jBtnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCosActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.cos(ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnCosActionPerformed

    private void jBtnCoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCoshActionPerformed
         double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.cosh(ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnCoshActionPerformed

    private void jBtnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTanActionPerformed
         double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.tan(ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnTanActionPerformed

    private void jBtnTanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTanhActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.tanh(ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnTanhActionPerformed

    private void jBtnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPiActionPerformed
        double ops;
        ops = ( 3.1415926535897932384626433832795);
         jTextDisplay.setText(String.valueOf(ops));
        
    }//GEN-LAST:event_jBtnPiActionPerformed

    private void jBtnRundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRundActionPerformed
         double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.round(ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnRundActionPerformed

    private void jBtnCbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCbrActionPerformed
         double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.cbrt(ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnCbrActionPerformed

    private void jBtnXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnXYActionPerformed
       double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.pow(ops, ops);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnXYActionPerformed

    private void jBtnX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnX2ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.pow(ops, 2);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnX2ActionPerformed

    private void jBtnX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnX3ActionPerformed
         double ops = Double.parseDouble(String.valueOf(jTextDisplay.getText()));
        ops = Math.pow(ops, 3);
        jTextDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnX3ActionPerformed

    private void jBtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualsActionPerformed
       String Answer;
       SecondNum = Double.parseDouble(jTextDisplay.getText());
       if ( operations == "+")
       {
           Result = FirstNum + SecondNum;
           Answer = String.format("%.2f", Result);
           jTextDisplay.setText(Answer);
       }
       
       else if ( operations == "-")
       {
            Result = FirstNum - SecondNum;
           Answer = String.format("%.2f", Result);
           jTextDisplay.setText(Answer);
       }
          
       else if ( operations == "*")
       {
            Result = FirstNum * SecondNum;
           Answer = String.format("%.2f", Result);
           jTextDisplay.setText(Answer);
       }
          
       else if ( operations == "/")
       {
            Result = FirstNum / SecondNum;
           Answer = String.format("%.2f", Result);
           jTextDisplay.setText(Answer);
       }
        else if ( operations == "%")
       {
            Result = FirstNum % SecondNum;
           Answer = String.format("%.2f", Result);
           jTextDisplay.setText(Answer);
       }
    }//GEN-LAST:event_jBtnEqualsActionPerformed

    private void jBtnBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBinActionPerformed
        int a = Integer.parseInt(jTextDisplay.getText());
        jTextDisplay.setText(Integer.toString(a, 2));
    }//GEN-LAST:event_jBtnBinActionPerformed

    private void jBtnHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHexActionPerformed
        int a = Integer.parseInt(jTextDisplay.getText());
        jTextDisplay.setText(Integer.toString(a, 16));
    }//GEN-LAST:event_jBtnHexActionPerformed

    private void jTextDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDisplayKeyTyped
       char c =evt.getKeyChar();
       
       if ((!Character.isDigit(c)|| (c== KeyEvent.VK_BACK_SPACE))
           || (c== KeyEvent.VK_DELETE))
       {
           getToolkit().beep();
           evt.consume();
       }
    }//GEN-LAST:event_jTextDisplayKeyTyped

    private void jBtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlusActionPerformed
         FirstNum = Double.parseDouble(jTextDisplay.getText());
         jTextDisplay.setText(null);
         operations=("+");
    }//GEN-LAST:event_jBtnPlusActionPerformed

    private void jBtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiplyActionPerformed
         FirstNum = Double.parseDouble(jTextDisplay.getText());
         jTextDisplay.setText(null);
         operations=("*");
    }//GEN-LAST:event_jBtnMultiplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scientific_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scientific_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scientific_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scientific_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scientific_cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnBin;
    private javax.swing.JButton jBtnCbr;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnCos;
    private javax.swing.JButton jBtnCosh;
    private javax.swing.JButton jBtnDecimal;
    private javax.swing.JButton jBtnDivide;
    private javax.swing.JButton jBtnEquals;
    private javax.swing.JButton jBtnHex;
    private javax.swing.JButton jBtnLog;
    private javax.swing.JButton jBtnMinus;
    private javax.swing.JButton jBtnMultiply;
    private javax.swing.JButton jBtnPi;
    private javax.swing.JButton jBtnPlus;
    private javax.swing.JButton jBtnRund;
    private javax.swing.JButton jBtnSin;
    private javax.swing.JButton jBtnSinh;
    private javax.swing.JButton jBtnSquareRoot;
    private javax.swing.JButton jBtnTan;
    private javax.swing.JButton jBtnTanh;
    private javax.swing.JButton jBtnX2;
    private javax.swing.JButton jBtnX3;
    private javax.swing.JButton jBtnXY;
    private javax.swing.JButton jButton13;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextDisplay;
    private javax.swing.JButton jbtnBackspace;
    // End of variables declaration//GEN-END:variables
}
